dependencies:
- name: bdd-sbhg-1582433207
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: bdd-spring-1582431983
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
